server:
  port: 8000

logging:
  level:
    root: INFO

spring:
  main:
    banner-mode: 'off'

---

spring:
  profiles: development
  thymeleaf:
    cache: false

logging:
  level:
    root: DEBUG

---

spring:
  profiles: production

logging:
  path: /tmp/
  file: Log.log
  level:
    root: WARN

